// Code generated by options-gen v0.58.0. DO NOT EDIT.

package eventadapter

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithProcessors(opt map[string]EventAdapter) OptOptionsSetter {
	return func(o *Options) { o.processors = opt }
}

func (o *Options) Validate() error {
	return nil
}
