// Code generated by options-gen v0.58.0. DO NOT EDIT.

package handlers

import (
	fmt461e464ebed9 "fmt"
	"time"

	logger "github.com/assurrussa/gologger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"

	websocketstream "github.com/assurrussa/gowebsocket/websocketstream"
	eventadapter "github.com/assurrussa/gowebsocket/websocketstream/eventadapter"
	eventprocessor "github.com/assurrussa/gowebsocket/websocketstream/eventprocessor"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	logger logger.Logger,
	eventStream eventStream,
	upgrader websocketstream.Upgrader,
	shutdownCh <-chan struct{},
	userIDCtxKey string,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.pingPeriod, _ = time.ParseDuration("10s")

	o.logger = logger
	o.eventStream = eventStream
	o.upgrader = upgrader
	o.shutdownCh = shutdownCh
	o.userIDCtxKey = userIDCtxKey

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithPingPeriod(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.pingPeriod = opt }
}

func WithEventProcessors(opt map[string]eventprocessor.EventProcessor) OptOptionsSetter {
	return func(o *Options) { o.eventProcessors = opt }
}

func WithEventAdapters(opt map[string]eventadapter.EventAdapter) OptOptionsSetter {
	return func(o *Options) { o.eventAdapters = opt }
}

func WithReadEventProcessor(opt websocketstream.ReadEventProcessor) OptOptionsSetter {
	return func(o *Options) { o.readEventProcessor = opt }
}

func WithEventWriter(opt websocketstream.EventWriter) OptOptionsSetter {
	return func(o *Options) { o.eventWriter = opt }
}

func WithEventAdapter(opt websocketstream.EventAdapter) OptOptionsSetter {
	return func(o *Options) { o.eventAdapter = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("pingPeriod", _validate_Options_pingPeriod(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("eventStream", _validate_Options_eventStream(o)))
	errs.Add(errors461e464ebed9.NewValidationError("upgrader", _validate_Options_upgrader(o)))
	errs.Add(errors461e464ebed9.NewValidationError("shutdownCh", _validate_Options_shutdownCh(o)))
	errs.Add(errors461e464ebed9.NewValidationError("userIDCtxKey", _validate_Options_userIDCtxKey(o)))
	return errs.AsError()
}

func _validate_Options_pingPeriod(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.pingPeriod, "omitempty,min=100ms,max=30s"); err != nil {
		return fmt461e464ebed9.Errorf("field `pingPeriod` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_eventStream(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventStream, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventStream` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_upgrader(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.upgrader, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `upgrader` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_shutdownCh(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.shutdownCh, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `shutdownCh` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_userIDCtxKey(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.userIDCtxKey, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `userIDCtxKey` did not pass the test: %w", err)
	}
	return nil
}
