// Code generated by MockGen. DO NOT EDIT.
// Source: event_stream.go
//
// Generated by this command:
//
//	mockgen -source=event_stream.go -destination=mocks/event_stream_mock.gen.go -package=eventstreammocks
//

// Package eventstreammocks is a generated GoMock package.
package eventstreammocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	eventstream "github.com/assurrussa/gowebsocket/eventstream"
)

// MockEvent is a mock of Event interface.
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
	isgomock struct{}
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance.
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// EventID mocks base method.
func (m *MockEvent) EventID() eventstream.EventID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventID")
	ret0, _ := ret[0].(eventstream.EventID)
	return ret0
}

// EventID indicates an expected call of EventID.
func (mr *MockEventMockRecorder) EventID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventID", reflect.TypeOf((*MockEvent)(nil).EventID))
}

// EventName mocks base method.
func (m *MockEvent) EventName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventName")
	ret0, _ := ret[0].(string)
	return ret0
}

// EventName indicates an expected call of EventName.
func (mr *MockEventMockRecorder) EventName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventName", reflect.TypeOf((*MockEvent)(nil).EventName))
}

// Validate mocks base method.
func (m *MockEvent) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockEventMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockEvent)(nil).Validate))
}

// MockEventStream is a mock of EventStream interface.
type MockEventStream struct {
	ctrl     *gomock.Controller
	recorder *MockEventStreamMockRecorder
	isgomock struct{}
}

// MockEventStreamMockRecorder is the mock recorder for MockEventStream.
type MockEventStreamMockRecorder struct {
	mock *MockEventStream
}

// NewMockEventStream creates a new mock instance.
func NewMockEventStream(ctrl *gomock.Controller) *MockEventStream {
	mock := &MockEventStream{ctrl: ctrl}
	mock.recorder = &MockEventStreamMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStream) EXPECT() *MockEventStreamMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventStream) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventStreamMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventStream)(nil).Close))
}

// Publish mocks base method.
func (m *MockEventStream) Publish(ctx context.Context, userID eventstream.UserID, event eventstream.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, userID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventStreamMockRecorder) Publish(ctx, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventStream)(nil).Publish), ctx, userID, event)
}

// Subscribe mocks base method.
func (m *MockEventStream) Subscribe(ctx context.Context, userID eventstream.UserID) (<-chan eventstream.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, userID)
	ret0, _ := ret[0].(<-chan eventstream.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockEventStreamMockRecorder) Subscribe(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockEventStream)(nil).Subscribe), ctx, userID)
}
