// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/gowebsocket/websocketstream/eventprocessor (interfaces: EventProcessor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/processor_mock.gen.go -package=eventprocessormocks . EventProcessor
//

// Package eventprocessormocks is a generated GoMock package.
package eventprocessormocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	eventstream "github.com/assurrussa/gowebsocket/eventstream"
)

// MockEventProcessor is a mock of EventProcessor interface.
type MockEventProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockEventProcessorMockRecorder
	isgomock struct{}
}

// MockEventProcessorMockRecorder is the mock recorder for MockEventProcessor.
type MockEventProcessorMockRecorder struct {
	mock *MockEventProcessor
}

// NewMockEventProcessor creates a new mock instance.
func NewMockEventProcessor(ctrl *gomock.Controller) *MockEventProcessor {
	mock := &MockEventProcessor{ctrl: ctrl}
	mock.recorder = &MockEventProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventProcessor) EXPECT() *MockEventProcessorMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockEventProcessor) Handle(ctx context.Context, req eventstream.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockEventProcessorMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockEventProcessor)(nil).Handle), ctx, req)
}
