// Code generated by options-gen v0.58.0. DO NOT EDIT.

package eventprocessor

import (
	fmt461e464ebed9 "fmt"
	"time"

	logger "github.com/assurrussa/gologger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	logger logger.Logger,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.maxTimeWait, _ = time.ParseDuration("1s")

	o.logger = logger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithProcessors(opt map[string]EventProcessor) OptOptionsSetter {
	return func(o *Options) { o.processors = opt }
}

func WithMaxTimeWait(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.maxTimeWait = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	return errs.AsError()
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}
